version: '3.8'

services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: bluelab-kavita
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ./kavita-config:/config
      - ${DATA_DIR}/data/books:/books
      - ${DATA_DIR}/data/manga:/manga
      - ${DATA_DIR}/data/comics:/comics
    ports:
      - "${KAVITA_PORT:-5000}:5000"
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Kavita"
      - "bluelab.category=Books"
      - "bluelab.description=Digital library server for books, manga, and comics"
      - "bluelab.port=${KAVITA_PORT:-5000}"
      - "bluelab.subdomain=books"

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: bluelab-readarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ./readarr-config:/config
      - ${DATA_DIR}/data/books:/books
      - ${DATA_DIR}/data/media/downloads:/downloads
    ports:
      - "${READARR_PORT:-8787}:8787"
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Readarr"
      - "bluelab.category=Books"
      - "bluelab.description=Book collection manager and automatic downloader"
      - "bluelab.port=${READARR_PORT:-8787}"
      - "bluelab.subdomain=readarr"

networks:
  default:
    name: ${BLUELAB_NETWORK:-bluelab-network}
    external: true