---
# Homepage Configuration for BlueLab Stacks

title: ${DOMAIN_PREFIX^} Dashboard
subtitle: Personal Cloud & Media Server
headerStyle: clean
theme: dark
color: slate
target: _self
useEqualHeights: true

layout:
  Dashboard:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 2
  Media:
    style: row
    columns: 3
  Network:
    style: row
    columns: 2
  Management:
    style: row
    columns: 2

providers:
  longhorn:
    url: http://longhorn-frontend

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

settings:
  title: ${DOMAIN_PREFIX^} Dashboard
  headerStyle: clean
  theme: dark
  color: slate
  hideVersion: true
  target: _self
  cardBlur: md
  language: en
  hideErrors: false
  showStats: true
  fiveColumns: false
  statusStyle: "dot"
  favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/homepage.png