version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: bluelab-tailscale
    hostname: ${DOMAIN_PREFIX:-homelab}-server
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY:-}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
    volumes:
      - ./tailscale-data:/var/lib/tailscale
      - ./config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Tailscale"
      - "bluelab.category=Network"
      - "bluelab.description=Secure VPN tunnel"
      - "bluelab.port=none"
      - "bluelab.subdomain=vpn"

  adguard:
    image: adguard/adguardhome:latest
    container_name: bluelab-adguard
    hostname: ${DOMAIN_PREFIX:-homelab}-dns
    ports:
      - "${ADGUARD_PORT:-3001}:3000"
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf
      - ./config/adguard.yaml:/opt/adguardhome/conf/AdGuardHome.yaml
    restart: unless-stopped
    depends_on:
      - tailscale
    labels:
      - "bluelab.service=true"
      - "bluelab.name=AdGuard Home"
      - "bluelab.category=Network"
      - "bluelab.description=DNS server with ad-blocking"
      - "bluelab.port=${ADGUARD_PORT:-3001}"
      - "bluelab.subdomain=dns"

networks:
  default:
    name: ${BLUELAB_NETWORK:-bluelab-network}
    driver: bridge