version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: bluelab-homepage
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ./homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}:/data:ro
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Homepage"
      - "bluelab.category=Dashboard"
      - "bluelab.description=Main dashboard and service directory"
      - "bluelab.port=${HOMEPAGE_PORT:-3000}"
      - "bluelab.subdomain=home"

  dockge:
    image: louislam/dockge:1
    container_name: bluelab-dockge
    environment:
      - DOCKGE_STACKS_DIR=${DATA_DIR}/stacks
      - TZ=${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockge-data:/app/data
      - ${DATA_DIR}/stacks:/opt/stacks
    ports:
      - "${DOCKGE_PORT:-5001}:5001"
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Dockge"
      - "bluelab.category=Management"
      - "bluelab.description=Docker Compose stack manager"
      - "bluelab.port=${DOCKGE_PORT:-5001}"
      - "bluelab.subdomain=docker"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: bluelab-watchtower
    environment:
      - TZ=${TZ:-UTC}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_EMAIL_SERVER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_EMAIL_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL_USER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "bluelab.service=true"
      - "bluelab.name=Watchtower"
      - "bluelab.category=Management"
      - "bluelab.description=Automated container updates"

networks:
  default:
    name: ${BLUELAB_NETWORK:-bluelab-network}
    external: true